// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package messages;

public final class Messages {
	private Messages() {
	}

	public static void registerAllExtensions(
	    com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
	    com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface ResponderOrBuilder extends
	// @@protoc_insertion_point(interface_extends:user.Responder)
	    com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>string firstName = 1;</code>
		 */
		java.lang.String getFirstName();

		/**
		 * <code>string firstName = 1;</code>
		 */
		com.google.protobuf.ByteString getFirstNameBytes();

		/**
		 * <code>string lastname = 2;</code>
		 */
		java.lang.String getLastname();

		/**
		 * <code>string lastname = 2;</code>
		 */
		com.google.protobuf.ByteString getLastnameBytes();

		/**
		 * <code>string email = 3;</code>
		 */
		java.lang.String getEmail();

		/**
		 * <code>string email = 3;</code>
		 */
		com.google.protobuf.ByteString getEmailBytes();

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		java.util.List<java.lang.String> getQuestionsList();

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		int getQuestionsCount();

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		java.lang.String getQuestions(int index);

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		com.google.protobuf.ByteString getQuestionsBytes(int index);

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		java.util.List<java.lang.String> getAnswersList();

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		int getAnswersCount();

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		java.lang.String getAnswers(int index);

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		com.google.protobuf.ByteString getAnswersBytes(int index);
	}

	/**
	 * Protobuf type {@code user.Responder}
	 */
	public static final class Responder extends
	    com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:user.Responder)
	    ResponderOrBuilder {
		// Use Responder.newBuilder() to construct.
		private Responder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Responder() {
			firstName_ = "";
			lastname_ = "";
			email_ = "";
			questions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
			answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private Responder(com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						java.lang.String s = input.readStringRequireUtf8();

						firstName_ = s;
						break;
					}
					case 18: {
						java.lang.String s = input.readStringRequireUtf8();

						lastname_ = s;
						break;
					}
					case 26: {
						java.lang.String s = input.readStringRequireUtf8();

						email_ = s;
						break;
					}
					case 34: {
						java.lang.String s = input.readStringRequireUtf8();
						if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
							questions_ = new com.google.protobuf.LazyStringArrayList();
							mutable_bitField0_ |= 0x00000008;
						}
						questions_.add(s);
						break;
					}
					case 42: {
						java.lang.String s = input.readStringRequireUtf8();
						if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
							answers_ = new com.google.protobuf.LazyStringArrayList();
							mutable_bitField0_ |= 0x00000010;
						}
						answers_.add(s);
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
				    .setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
					questions_ = questions_.getUnmodifiableView();
				}
				if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
					answers_ = answers_.getUnmodifiableView();
				}
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Messages.internal_static_user_Responder_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return Messages.internal_static_user_Responder_fieldAccessorTable
			    .ensureFieldAccessorsInitialized(Messages.Responder.class,
			        Messages.Responder.Builder.class);
		}

		private int bitField0_;
		public static final int FIRSTNAME_FIELD_NUMBER = 1;
		private volatile java.lang.Object firstName_;

		/**
		 * <code>string firstName = 1;</code>
		 */
		public java.lang.String getFirstName() {
			java.lang.Object ref = firstName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				firstName_ = s;
				return s;
			}
		}

		/**
		 * <code>string firstName = 1;</code>
		 */
		public com.google.protobuf.ByteString getFirstNameBytes() {
			java.lang.Object ref = firstName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
				    .copyFromUtf8((java.lang.String) ref);
				firstName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int LASTNAME_FIELD_NUMBER = 2;
		private volatile java.lang.Object lastname_;

		/**
		 * <code>string lastname = 2;</code>
		 */
		public java.lang.String getLastname() {
			java.lang.Object ref = lastname_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				lastname_ = s;
				return s;
			}
		}

		/**
		 * <code>string lastname = 2;</code>
		 */
		public com.google.protobuf.ByteString getLastnameBytes() {
			java.lang.Object ref = lastname_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
				    .copyFromUtf8((java.lang.String) ref);
				lastname_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int EMAIL_FIELD_NUMBER = 3;
		private volatile java.lang.Object email_;

		/**
		 * <code>string email = 3;</code>
		 */
		public java.lang.String getEmail() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				email_ = s;
				return s;
			}
		}

		/**
		 * <code>string email = 3;</code>
		 */
		public com.google.protobuf.ByteString getEmailBytes() {
			java.lang.Object ref = email_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
				    .copyFromUtf8((java.lang.String) ref);
				email_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int QUESTIONS_FIELD_NUMBER = 4;
		private com.google.protobuf.LazyStringList questions_;

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		public com.google.protobuf.ProtocolStringList getQuestionsList() {
			return questions_;
		}

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		public int getQuestionsCount() {
			return questions_.size();
		}

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		public java.lang.String getQuestions(int index) {
			return questions_.get(index);
		}

		/**
		 * <code>repeated string questions = 4;</code>
		 */
		public com.google.protobuf.ByteString getQuestionsBytes(int index) {
			return questions_.getByteString(index);
		}

		public static final int ANSWERS_FIELD_NUMBER = 5;
		private com.google.protobuf.LazyStringList answers_;

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		public com.google.protobuf.ProtocolStringList getAnswersList() {
			return answers_;
		}

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		public int getAnswersCount() {
			return answers_.size();
		}

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		public java.lang.String getAnswers(int index) {
			return answers_.get(index);
		}

		/**
		 * <code>repeated string answers = 5;</code>
		 */
		public com.google.protobuf.ByteString getAnswersBytes(int index) {
			return answers_.getByteString(index);
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
		    throws java.io.IOException {
			if (!getFirstNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1,
				    firstName_);
			}
			if (!getLastnameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3
				    .writeString(output, 2, lastname_);
			}
			if (!getEmailBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
			}
			for (int i = 0; i < questions_.size(); i++) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4,
				    questions_.getRaw(i));
			}
			for (int i = 0; i < answers_.size(); i++) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 5,
				    answers_.getRaw(i));
			}
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!getFirstNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1,
				    firstName_);
			}
			if (!getLastnameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2,
				    lastname_);
			}
			if (!getEmailBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3,
				    email_);
			}
			{
				int dataSize = 0;
				for (int i = 0; i < questions_.size(); i++) {
					dataSize += computeStringSizeNoTag(questions_.getRaw(i));
				}
				size += dataSize;
				size += 1 * getQuestionsList().size();
			}
			{
				int dataSize = 0;
				for (int i = 0; i < answers_.size(); i++) {
					dataSize += computeStringSizeNoTag(answers_.getRaw(i));
				}
				size += dataSize;
				size += 1 * getAnswersList().size();
			}
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Messages.Responder)) {
				return super.equals(obj);
			}
			Messages.Responder other = (Messages.Responder) obj;

			boolean result = true;
			result = result && getFirstName().equals(other.getFirstName());
			result = result && getLastname().equals(other.getLastname());
			result = result && getEmail().equals(other.getEmail());
			result = result && getQuestionsList().equals(other.getQuestionsList());
			result = result && getAnswersList().equals(other.getAnswersList());
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
			hash = (53 * hash) + getFirstName().hashCode();
			hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
			hash = (53 * hash) + getLastname().hashCode();
			hash = (37 * hash) + EMAIL_FIELD_NUMBER;
			hash = (53 * hash) + getEmail().hashCode();
			if (getQuestionsCount() > 0) {
				hash = (37 * hash) + QUESTIONS_FIELD_NUMBER;
				hash = (53 * hash) + getQuestionsList().hashCode();
			}
			if (getAnswersCount() > 0) {
				hash = (37 * hash) + ANSWERS_FIELD_NUMBER;
				hash = (53 * hash) + getAnswersList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Messages.Responder parseFrom(java.nio.ByteBuffer data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.Responder parseFrom(java.nio.ByteBuffer data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.Responder parseFrom(
		    com.google.protobuf.ByteString data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.Responder parseFrom(
		    com.google.protobuf.ByteString data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.Responder parseFrom(byte[] data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.Responder parseFrom(byte[] data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.Responder parseFrom(java.io.InputStream input)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.Responder parseFrom(java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public static Messages.Responder parseDelimitedFrom(
		    java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input);
		}

		public static Messages.Responder parseDelimitedFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Messages.Responder parseFrom(
		    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.Responder parseFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Messages.Responder prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
			    .mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
		    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code user.Responder}
		 */
		public static final class Builder extends
		    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:user.Responder)
		    Messages.ResponderOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Messages.internal_static_user_Responder_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return Messages.internal_static_user_Responder_fieldAccessorTable
				    .ensureFieldAccessorsInitialized(Messages.Responder.class,
				        Messages.Responder.Builder.class);
			}

			// Construct using
			// Messages.Responder.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
			    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				firstName_ = "";

				lastname_ = "";

				email_ = "";

				questions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000008);
				answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000010);
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Messages.internal_static_user_Responder_descriptor;
			}

			public Messages.Responder getDefaultInstanceForType() {
				return Messages.Responder.getDefaultInstance();
			}

			public Messages.Responder build() {
				Messages.Responder result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Messages.Responder buildPartial() {
				Messages.Responder result = new Messages.Responder(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				result.firstName_ = firstName_;
				result.lastname_ = lastname_;
				result.email_ = email_;
				if (((bitField0_ & 0x00000008) == 0x00000008)) {
					questions_ = questions_.getUnmodifiableView();
					bitField0_ = (bitField0_ & ~0x00000008);
				}
				result.questions_ = questions_;
				if (((bitField0_ & 0x00000010) == 0x00000010)) {
					answers_ = answers_.getUnmodifiableView();
					bitField0_ = (bitField0_ & ~0x00000010);
				}
				result.answers_ = answers_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(
			    com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(
			    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, int index,
			    Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Messages.Responder) {
					return mergeFrom((Messages.Responder) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Messages.Responder other) {
				if (other == Messages.Responder.getDefaultInstance())
					return this;
				if (!other.getFirstName().isEmpty()) {
					firstName_ = other.firstName_;
					onChanged();
				}
				if (!other.getLastname().isEmpty()) {
					lastname_ = other.lastname_;
					onChanged();
				}
				if (!other.getEmail().isEmpty()) {
					email_ = other.email_;
					onChanged();
				}
				if (!other.questions_.isEmpty()) {
					if (questions_.isEmpty()) {
						questions_ = other.questions_;
						bitField0_ = (bitField0_ & ~0x00000008);
					} else {
						ensureQuestionsIsMutable();
						questions_.addAll(other.questions_);
					}
					onChanged();
				}
				if (!other.answers_.isEmpty()) {
					if (answers_.isEmpty()) {
						answers_ = other.answers_;
						bitField0_ = (bitField0_ & ~0x00000010);
					} else {
						ensureAnswersIsMutable();
						answers_.addAll(other.answers_);
					}
					onChanged();
				}
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws java.io.IOException {
				Messages.Responder parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Messages.Responder) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.lang.Object firstName_ = "";

			/**
			 * <code>string firstName = 1;</code>
			 */
			public java.lang.String getFirstName() {
				java.lang.Object ref = firstName_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					firstName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string firstName = 1;</code>
			 */
			public com.google.protobuf.ByteString getFirstNameBytes() {
				java.lang.Object ref = firstName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					    .copyFromUtf8((java.lang.String) ref);
					firstName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string firstName = 1;</code>
			 */
			public Builder setFirstName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				firstName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string firstName = 1;</code>
			 */
			public Builder clearFirstName() {

				firstName_ = getDefaultInstance().getFirstName();
				onChanged();
				return this;
			}

			/**
			 * <code>string firstName = 1;</code>
			 */
			public Builder setFirstNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				firstName_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object lastname_ = "";

			/**
			 * <code>string lastname = 2;</code>
			 */
			public java.lang.String getLastname() {
				java.lang.Object ref = lastname_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					lastname_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string lastname = 2;</code>
			 */
			public com.google.protobuf.ByteString getLastnameBytes() {
				java.lang.Object ref = lastname_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					    .copyFromUtf8((java.lang.String) ref);
					lastname_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string lastname = 2;</code>
			 */
			public Builder setLastname(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				lastname_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string lastname = 2;</code>
			 */
			public Builder clearLastname() {

				lastname_ = getDefaultInstance().getLastname();
				onChanged();
				return this;
			}

			/**
			 * <code>string lastname = 2;</code>
			 */
			public Builder setLastnameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				lastname_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object email_ = "";

			/**
			 * <code>string email = 3;</code>
			 */
			public java.lang.String getEmail() {
				java.lang.Object ref = email_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					email_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public com.google.protobuf.ByteString getEmailBytes() {
				java.lang.Object ref = email_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
					    .copyFromUtf8((java.lang.String) ref);
					email_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder setEmail(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				email_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder clearEmail() {

				email_ = getDefaultInstance().getEmail();
				onChanged();
				return this;
			}

			/**
			 * <code>string email = 3;</code>
			 */
			public Builder setEmailBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				email_ = value;
				onChanged();
				return this;
			}

			private com.google.protobuf.LazyStringList questions_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureQuestionsIsMutable() {
				if (!((bitField0_ & 0x00000008) == 0x00000008)) {
					questions_ = new com.google.protobuf.LazyStringArrayList(questions_);
					bitField0_ |= 0x00000008;
				}
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public com.google.protobuf.ProtocolStringList getQuestionsList() {
				return questions_.getUnmodifiableView();
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public int getQuestionsCount() {
				return questions_.size();
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public java.lang.String getQuestions(int index) {
				return questions_.get(index);
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public com.google.protobuf.ByteString getQuestionsBytes(int index) {
				return questions_.getByteString(index);
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public Builder setQuestions(int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureQuestionsIsMutable();
				questions_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public Builder addQuestions(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureQuestionsIsMutable();
				questions_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public Builder addAllQuestions(java.lang.Iterable<java.lang.String> values) {
				ensureQuestionsIsMutable();
				com.google.protobuf.AbstractMessageLite.Builder.addAll(values,
				    questions_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public Builder clearQuestions() {
				questions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000008);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string questions = 4;</code>
			 */
			public Builder addQuestionsBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				ensureQuestionsIsMutable();
				questions_.add(value);
				onChanged();
				return this;
			}

			private com.google.protobuf.LazyStringList answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;

			private void ensureAnswersIsMutable() {
				if (!((bitField0_ & 0x00000010) == 0x00000010)) {
					answers_ = new com.google.protobuf.LazyStringArrayList(answers_);
					bitField0_ |= 0x00000010;
				}
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public com.google.protobuf.ProtocolStringList getAnswersList() {
				return answers_.getUnmodifiableView();
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public int getAnswersCount() {
				return answers_.size();
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public java.lang.String getAnswers(int index) {
				return answers_.get(index);
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public com.google.protobuf.ByteString getAnswersBytes(int index) {
				return answers_.getByteString(index);
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public Builder setAnswers(int index, java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureAnswersIsMutable();
				answers_.set(index, value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public Builder addAnswers(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				ensureAnswersIsMutable();
				answers_.add(value);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public Builder addAllAnswers(java.lang.Iterable<java.lang.String> values) {
				ensureAnswersIsMutable();
				com.google.protobuf.AbstractMessageLite.Builder
				    .addAll(values, answers_);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public Builder clearAnswers() {
				answers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000010);
				onChanged();
				return this;
			}

			/**
			 * <code>repeated string answers = 5;</code>
			 */
			public Builder addAnswersBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);
				ensureAnswersIsMutable();
				answers_.add(value);
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			public final Builder mergeUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:user.Responder)
		}

		// @@protoc_insertion_point(class_scope:user.Responder)
		private static final Messages.Responder DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new Messages.Responder();
		}

		public static Messages.Responder getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Responder> PARSER = new com.google.protobuf.AbstractParser<Responder>() {
			public Responder parsePartialFrom(
			    com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws com.google.protobuf.InvalidProtocolBufferException {
				return new Responder(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Responder> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Responder> getParserForType() {
			return PARSER;
		}

		public Messages.Responder getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ResponderRequestOrBuilder extends
	// @@protoc_insertion_point(interface_extends:user.ResponderRequest)
	    com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		java.util.List<Messages.Responder> getResponderList();

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		Messages.Responder getResponder(int index);

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		int getResponderCount();

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		java.util.List<? extends Messages.ResponderOrBuilder> getResponderOrBuilderList();

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		Messages.ResponderOrBuilder getResponderOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code user.ResponderRequest}
	 */
	public static final class ResponderRequest extends
	    com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:user.ResponderRequest)
	    ResponderRequestOrBuilder {
		// Use ResponderRequest.newBuilder() to construct.
		private ResponderRequest(
		    com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private ResponderRequest() {
			responder_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private ResponderRequest(com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
							responder_ = new java.util.ArrayList<Messages.Responder>();
							mutable_bitField0_ |= 0x00000001;
						}
						responder_.add(input.readMessage(Messages.Responder.parser(),
						    extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
				    .setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
					responder_ = java.util.Collections.unmodifiableList(responder_);
				}
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Messages.internal_static_user_ResponderRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return Messages.internal_static_user_ResponderRequest_fieldAccessorTable
			    .ensureFieldAccessorsInitialized(Messages.ResponderRequest.class,
			        Messages.ResponderRequest.Builder.class);
		}

		public static final int RESPONDER_FIELD_NUMBER = 1;
		private java.util.List<Messages.Responder> responder_;

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		public java.util.List<Messages.Responder> getResponderList() {
			return responder_;
		}

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		public java.util.List<? extends Messages.ResponderOrBuilder> getResponderOrBuilderList() {
			return responder_;
		}

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		public int getResponderCount() {
			return responder_.size();
		}

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		public Messages.Responder getResponder(int index) {
			return responder_.get(index);
		}

		/**
		 * <code>repeated .user.Responder responder = 1;</code>
		 */
		public Messages.ResponderOrBuilder getResponderOrBuilder(int index) {
			return responder_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
		    throws java.io.IOException {
			for (int i = 0; i < responder_.size(); i++) {
				output.writeMessage(1, responder_.get(i));
			}
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < responder_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(1,
				    responder_.get(i));
			}
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Messages.ResponderRequest)) {
				return super.equals(obj);
			}
			Messages.ResponderRequest other = (Messages.ResponderRequest) obj;

			boolean result = true;
			result = result && getResponderList().equals(other.getResponderList());
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			if (getResponderCount() > 0) {
				hash = (37 * hash) + RESPONDER_FIELD_NUMBER;
				hash = (53 * hash) + getResponderList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Messages.ResponderRequest parseFrom(java.nio.ByteBuffer data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderRequest parseFrom(java.nio.ByteBuffer data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderRequest parseFrom(
		    com.google.protobuf.ByteString data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderRequest parseFrom(
		    com.google.protobuf.ByteString data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderRequest parseFrom(byte[] data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderRequest parseFrom(byte[] data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderRequest parseFrom(java.io.InputStream input)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.ResponderRequest parseFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public static Messages.ResponderRequest parseDelimitedFrom(
		    java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input);
		}

		public static Messages.ResponderRequest parseDelimitedFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Messages.ResponderRequest parseFrom(
		    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.ResponderRequest parseFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Messages.ResponderRequest prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
			    .mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
		    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code user.ResponderRequest}
		 */
		public static final class Builder extends
		    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:user.ResponderRequest)
		    Messages.ResponderRequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Messages.internal_static_user_ResponderRequest_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return Messages.internal_static_user_ResponderRequest_fieldAccessorTable
				    .ensureFieldAccessorsInitialized(Messages.ResponderRequest.class,
				        Messages.ResponderRequest.Builder.class);
			}

			// Construct using
			// Messages.ResponderRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
			    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					getResponderFieldBuilder();
				}
			}

			public Builder clear() {
				super.clear();
				if (responderBuilder_ == null) {
					responder_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					responderBuilder_.clear();
				}
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Messages.internal_static_user_ResponderRequest_descriptor;
			}

			public Messages.ResponderRequest getDefaultInstanceForType() {
				return Messages.ResponderRequest.getDefaultInstance();
			}

			public Messages.ResponderRequest build() {
				Messages.ResponderRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Messages.ResponderRequest buildPartial() {
				Messages.ResponderRequest result = new Messages.ResponderRequest(this);
				int from_bitField0_ = bitField0_;
				if (responderBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						responder_ = java.util.Collections.unmodifiableList(responder_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.responder_ = responder_;
				} else {
					result.responder_ = responderBuilder_.build();
				}
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(
			    com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(
			    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, int index,
			    Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Messages.ResponderRequest) {
					return mergeFrom((Messages.ResponderRequest) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Messages.ResponderRequest other) {
				if (other == Messages.ResponderRequest.getDefaultInstance())
					return this;
				if (responderBuilder_ == null) {
					if (!other.responder_.isEmpty()) {
						if (responder_.isEmpty()) {
							responder_ = other.responder_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureResponderIsMutable();
							responder_.addAll(other.responder_);
						}
						onChanged();
					}
				} else {
					if (!other.responder_.isEmpty()) {
						if (responderBuilder_.isEmpty()) {
							responderBuilder_.dispose();
							responderBuilder_ = null;
							responder_ = other.responder_;
							bitField0_ = (bitField0_ & ~0x00000001);
							responderBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getResponderFieldBuilder()
							    : null;
						} else {
							responderBuilder_.addAllMessages(other.responder_);
						}
					}
				}
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws java.io.IOException {
				Messages.ResponderRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Messages.ResponderRequest) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private java.util.List<Messages.Responder> responder_ = java.util.Collections
			    .emptyList();

			private void ensureResponderIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					responder_ = new java.util.ArrayList<Messages.Responder>(responder_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<Messages.Responder, Messages.Responder.Builder, Messages.ResponderOrBuilder> responderBuilder_;

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public java.util.List<Messages.Responder> getResponderList() {
				if (responderBuilder_ == null) {
					return java.util.Collections.unmodifiableList(responder_);
				} else {
					return responderBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public int getResponderCount() {
				if (responderBuilder_ == null) {
					return responder_.size();
				} else {
					return responderBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Messages.Responder getResponder(int index) {
				if (responderBuilder_ == null) {
					return responder_.get(index);
				} else {
					return responderBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder setResponder(int index, Messages.Responder value) {
				if (responderBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureResponderIsMutable();
					responder_.set(index, value);
					onChanged();
				} else {
					responderBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder setResponder(int index,
			    Messages.Responder.Builder builderForValue) {
				if (responderBuilder_ == null) {
					ensureResponderIsMutable();
					responder_.set(index, builderForValue.build());
					onChanged();
				} else {
					responderBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder addResponder(Messages.Responder value) {
				if (responderBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureResponderIsMutable();
					responder_.add(value);
					onChanged();
				} else {
					responderBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder addResponder(int index, Messages.Responder value) {
				if (responderBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureResponderIsMutable();
					responder_.add(index, value);
					onChanged();
				} else {
					responderBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder addResponder(Messages.Responder.Builder builderForValue) {
				if (responderBuilder_ == null) {
					ensureResponderIsMutable();
					responder_.add(builderForValue.build());
					onChanged();
				} else {
					responderBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder addResponder(int index,
			    Messages.Responder.Builder builderForValue) {
				if (responderBuilder_ == null) {
					ensureResponderIsMutable();
					responder_.add(index, builderForValue.build());
					onChanged();
				} else {
					responderBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder addAllResponder(
			    java.lang.Iterable<? extends Messages.Responder> values) {
				if (responderBuilder_ == null) {
					ensureResponderIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values,
					    responder_);
					onChanged();
				} else {
					responderBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder clearResponder() {
				if (responderBuilder_ == null) {
					responder_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					responderBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Builder removeResponder(int index) {
				if (responderBuilder_ == null) {
					ensureResponderIsMutable();
					responder_.remove(index);
					onChanged();
				} else {
					responderBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Messages.Responder.Builder getResponderBuilder(int index) {
				return getResponderFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Messages.ResponderOrBuilder getResponderOrBuilder(int index) {
				if (responderBuilder_ == null) {
					return responder_.get(index);
				} else {
					return responderBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public java.util.List<? extends Messages.ResponderOrBuilder> getResponderOrBuilderList() {
				if (responderBuilder_ != null) {
					return responderBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(responder_);
				}
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Messages.Responder.Builder addResponderBuilder() {
				return getResponderFieldBuilder().addBuilder(
				    Messages.Responder.getDefaultInstance());
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public Messages.Responder.Builder addResponderBuilder(int index) {
				return getResponderFieldBuilder().addBuilder(index,
				    Messages.Responder.getDefaultInstance());
			}

			/**
			 * <code>repeated .user.Responder responder = 1;</code>
			 */
			public java.util.List<Messages.Responder.Builder> getResponderBuilderList() {
				return getResponderFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<Messages.Responder, Messages.Responder.Builder, Messages.ResponderOrBuilder> getResponderFieldBuilder() {
				if (responderBuilder_ == null) {
					responderBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<Messages.Responder, Messages.Responder.Builder, Messages.ResponderOrBuilder>(
					    responder_, ((bitField0_ & 0x00000001) == 0x00000001),
					    getParentForChildren(), isClean());
					responder_ = null;
				}
				return responderBuilder_;
			}

			public final Builder setUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			public final Builder mergeUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:user.ResponderRequest)
		}

		// @@protoc_insertion_point(class_scope:user.ResponderRequest)
		private static final Messages.ResponderRequest DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new Messages.ResponderRequest();
		}

		public static Messages.ResponderRequest getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<ResponderRequest> PARSER = new com.google.protobuf.AbstractParser<ResponderRequest>() {
			public ResponderRequest parsePartialFrom(
			    com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws com.google.protobuf.InvalidProtocolBufferException {
				return new ResponderRequest(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<ResponderRequest> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<ResponderRequest> getParserForType() {
			return PARSER;
		}

		public Messages.ResponderRequest getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	public interface ResponderResponseOrBuilder extends
	// @@protoc_insertion_point(interface_extends:user.ResponderResponse)
	    com.google.protobuf.MessageOrBuilder {
	}

	/**
	 * Protobuf type {@code user.ResponderResponse}
	 */
	public static final class ResponderResponse extends
	    com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:user.ResponderResponse)
	    ResponderResponseOrBuilder {
		// Use ResponderResponse.newBuilder() to construct.
		private ResponderResponse(
		    com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private ResponderResponse() {
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private ResponderResponse(com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
				    .setUnfinishedMessage(this);
			} finally {
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return Messages.internal_static_user_ResponderResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return Messages.internal_static_user_ResponderResponse_fieldAccessorTable
			    .ensureFieldAccessorsInitialized(Messages.ResponderResponse.class,
			        Messages.ResponderResponse.Builder.class);
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
		    throws java.io.IOException {
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof Messages.ResponderResponse)) {
				return super.equals(obj);
			}
			Messages.ResponderResponse other = (Messages.ResponderResponse) obj;

			boolean result = true;
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static Messages.ResponderResponse parseFrom(java.nio.ByteBuffer data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderResponse parseFrom(
		    java.nio.ByteBuffer data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderResponse parseFrom(
		    com.google.protobuf.ByteString data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderResponse parseFrom(
		    com.google.protobuf.ByteString data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderResponse parseFrom(byte[] data)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static Messages.ResponderResponse parseFrom(byte[] data,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static Messages.ResponderResponse parseFrom(java.io.InputStream input)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.ResponderResponse parseFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public static Messages.ResponderResponse parseDelimitedFrom(
		    java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input);
		}

		public static Messages.ResponderResponse parseDelimitedFrom(
		    java.io.InputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
			    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static Messages.ResponderResponse parseFrom(
		    com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input);
		}

		public static Messages.ResponderResponse parseFrom(
		    com.google.protobuf.CodedInputStream input,
		    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
		    throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
			    PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(Messages.ResponderResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
			    .mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
		    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code user.ResponderResponse}
		 */
		public static final class Builder extends
		    com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:user.ResponderResponse)
		    Messages.ResponderResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return Messages.internal_static_user_ResponderResponse_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return Messages.internal_static_user_ResponderResponse_fieldAccessorTable
				    .ensureFieldAccessorsInitialized(Messages.ResponderResponse.class,
				        Messages.ResponderResponse.Builder.class);
			}

			// Construct using
			// Messages.ResponderResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
			    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return Messages.internal_static_user_ResponderResponse_descriptor;
			}

			public Messages.ResponderResponse getDefaultInstanceForType() {
				return Messages.ResponderResponse.getDefaultInstance();
			}

			public Messages.ResponderResponse build() {
				Messages.ResponderResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public Messages.ResponderResponse buildPartial() {
				Messages.ResponderResponse result = new Messages.ResponderResponse(this);
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(
			    com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(
			    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, int index,
			    Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(
			    com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof Messages.ResponderResponse) {
					return mergeFrom((Messages.ResponderResponse) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(Messages.ResponderResponse other) {
				if (other == Messages.ResponderResponse.getDefaultInstance())
					return this;
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws java.io.IOException {
				Messages.ResponderResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (Messages.ResponderResponse) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			public final Builder setUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			public final Builder mergeUnknownFields(
			    final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:user.ResponderResponse)
		}

		// @@protoc_insertion_point(class_scope:user.ResponderResponse)
		private static final Messages.ResponderResponse DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new Messages.ResponderResponse();
		}

		public static Messages.ResponderResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<ResponderResponse> PARSER = new com.google.protobuf.AbstractParser<ResponderResponse>() {
			public ResponderResponse parsePartialFrom(
			    com.google.protobuf.CodedInputStream input,
			    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			    throws com.google.protobuf.InvalidProtocolBufferException {
				return new ResponderResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<ResponderResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<ResponderResponse> getParserForType() {
			return PARSER;
		}

		public Messages.ResponderResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_user_Responder_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_user_Responder_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_user_ResponderRequest_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_user_ResponderRequest_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_user_ResponderResponse_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_user_ResponderResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\016messages.proto\022\004user\"c\n\tResponder\022\021\n\tf"
		    + "irstName\030\001 \001(\t\022\020\n\010lastname\030\002 \001(\t\022\r\n\005emai"
		    + "l\030\003 \001(\t\022\021\n\tquestions\030\004 \003(\t\022\017\n\007answers\030\005 "
		    + "\003(\t\"6\n\020ResponderRequest\022\"\n\tresponder\030\001 \003"
		    + "(\0132\017.user.Responder\"\023\n\021ResponderResponse"
		    + "2V\n\020ResponderService\022B\n\017NotifyResponder\022"
		    + "\026.user.ResponderRequest\032\027.user.Responder"
		    + "ResponseB#\n!com.github.KCulture.Notified" + ".grpcb\006proto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
			    com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
		    .internalBuildGeneratedFileFrom(descriptorData,
		        new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_user_Responder_descriptor = getDescriptor()
		    .getMessageTypes().get(0);
		internal_static_user_Responder_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		    internal_static_user_Responder_descriptor, new java.lang.String[] {
		        "FirstName", "Lastname", "Email", "Questions", "Answers", });
		internal_static_user_ResponderRequest_descriptor = getDescriptor()
		    .getMessageTypes().get(1);
		internal_static_user_ResponderRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		    internal_static_user_ResponderRequest_descriptor,
		    new java.lang.String[] { "Responder", });
		internal_static_user_ResponderResponse_descriptor = getDescriptor()
		    .getMessageTypes().get(2);
		internal_static_user_ResponderResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
		    internal_static_user_ResponderResponse_descriptor,
		    new java.lang.String[] {});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
